# Alcritty colors
# Cutesome Colorscheme

colors:
  primary:
    background: '#ffffff'
    foreground: '#121212'
  cursor:
    text:   CellForeground
    cursor: '#616161'
  bright:
    black:   '#121212'
    red:     '#ff5252'
    green:   '#00c853'
    yellow:  '#f0ca3c'
    blue:    '#448aff'
    magenta: '#7c4dff'
    cyan:    '#18ffff'
    white:   '#bdbdbd'
  normal:
    black:   '#121212'
    red:     '#ff5252'
    green:   '#00c853'
    yellow:  '#f0ca3c'
    blue:    '#448aff'
    magenta: '#7c4dff'
    cyan:    '#18ffff'
    white:   '#000000'
