## Color
import:
- ~/.config/alacritty/colors-material.yml
- ~/.config/alacritty/fonts.yml

## env vars
env:
  TERM: xterm-256color

## window settings
window:
  opacity: 1
  padding:
    x: 50
    y: 40


# Class (window name)
class:
  instance: Alacritty
  general: Alacritty

# Scrolling
scrolling:
  history: 10000
  multiplier: 3

# Visual
visual_bell:
  animation: EaseOutExpo
  duration: 0.5
  color: "#e4c9af"

# Selection?
selection:
  semantic_escape_chars: ",│`|:\"' ()[]{}<>\t"
  save_to_clipboard: true

# writing thing (cursor) 
cursor:
  style: 'Block'

# def Shell
shell:
  program: /usr/bin/zsh

# Mouse config
mouse:
  double_click: { threshold: 300 }
  triple_click: { threshold: 300 }
  hide_when_typing: true

# General config
live_config_reload: true
draw_bold_text_with_bright_colors: true
